# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f172fb10775843753d6cfed37c0eeb02b321fe137a8402fefb1916653cbcc0124a0e1360a1d5a8f605418f8be4ed5aa8d74c922b8e9906b1210664ef688d7c2f

test:
  secret_key_base: acad63008e2e6df383ff917879d461b02994fb3f2dd66b267f5fa56f56974900f21ee68b3e44ce10bdc9d7130e0e4c2885982a474cbdffafb09cf9694230f352

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
